### ISSUE TITLE
An enviromental requirements yml would help a lot!

### ISSUE THREAD

**Issue by DaHenz** [phbradley/alphafold_finetune#7]
Hi, may you upload the required packages or a yml file from your running environment? This would help a lot with installation. Many thanks!

**Comment by phbradley** [comment]
Hi there, sorry for the confusion-- I have had trouble finding a single yml file that works consistently across platforms. But check out this issue and see if the discussion there will help:

https://github.com/phbradley/alphafold_finetune/issues/2
